plugins {
    id 'com.android.application'
}

android {
    namespace 'com.usv.matchanalyzer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.usv.matchanalyzer.release1'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    signingConfigs {
        release {
            def ksPath = System.getenv('USV_KEYSTORE_PATH')
            if (ksPath != null) {
                storeFile file(ksPath)
                storePassword System.getenv('USV_STORE_PASSWORD')
                keyAlias System.getenv('USV_KEY_ALIAS')
                keyPassword System.getenv('USV_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
